name: Metrics
on:
  # Update otomatis setiap jam 00:00 WIB (kurang lebih)
  schedule: [{cron: "0 17 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token GitHub (Otomatis ada, tidak perlu diapa-apakan)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opsi Pengguna
          user: mohammadakbarr18
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          
          # Tampilan (Dark Mode Modern)
          config_order: base.header, isocalendar, languages, habits
          output_action: gist
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Plugin: Kalender 3D (Isocalendar) - Pengganti Streak yang sering error
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Plugin: Bahasa Pemrograman (Tampilan Keren)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          
          # Plugin: Kebiasaan Coding (Jam berapa sering coding)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
