name: Metrics
on:
  # Update setiap jam 00:00 WIB
  schedule: [{cron: "0 17 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # --- Opsi Pengguna ---
          user: mohammadakbarr18
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          
          # --- Konfigurasi Penyimpanan (INI YANG DIPERBAIKI) ---
          # Kita ubah dari 'gist' menjadi 'commit' agar file masuk ke repo
          output_action: commit
          committer_branch: metrics
          committer_message: "Update metrics display"
          filename: github-metrics.svg

          # --- Plugin Tambahan (3D & Coding Habits) ---
          config_order: base.header, isocalendar, languages, habits
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
